### ISSUE TITLE
could you help me ?why I faild to use javascript to alert() jason data

### ISSUE THREAD

**Issue by Archerlib** [rogerxu/rogerxu.github.io#107]
it's alert null when alert() out of function(), but it's ok when alert in the function above the for().
i've var gloable variable data in the beginning and i have set asyn:false. 
---------------
var data=new Array();
 $(document).ready(function(){
    $.ajax({
        async:false,
        type:"post",
        dataType:"json",
        url:"/Uhouse/uhouse/index.php/Home/Index/marker",
        success:function(result){
            var json=result.data;
             $.each(json, function(idx, obj) {
                for(i=0;i<json.length;i++){
                  data[i] =obj.rent_condo_loc;
                  
                }
                
            });
        }
    });
    
 }); 

  alert(data);

**Comment by rogerxu** [comment]
Please format your code properly when you ask a question.

```javascript
var data=new Array();
 $(document).ready(function(){
    $.ajax({
        async:false,
        type:"post",
        dataType:"json",
        url:"/Uhouse/uhouse/index.php/Home/Index/marker",
        success:function(result){
            var json=result.data;
             $.each(json, function(idx, obj) {
                for(i=0;i<json.length;i++){
                  data[i] =obj.rent_condo_loc;
                  
                }
                
            });
        }
    });
    
 }); 

  alert(data);
```
