### ISSUE TITLE
自卑与超越

### ISSUE THREAD

**Issue by rogerxu** [rogerxu/rogerxu.github.io#140]
[自卑与超越 (豆瓣)](https://book.douban.com/subject/3389960/)

- [x] 一、生活的意义
- [x] 二、心灵与肉体
- [x] 三、自卑感和优越感
- [x] 四、童年记忆
- [x] 五、梦
- [x] 六、家庭的影响
- [x] 七、学校的影响
- [x] 八、青春期
- [x] 九、犯罪及其预防
- [x] 十、职业
- [x] 十一、个体与社会
- [x] 十二、爱情与婚姻

**Comment by rogerxu** [comment]
# 一、生活的意义

## 1. 生活于你的意义

## 2. 生命中的三大问题

- 我与地球
- 我和种族
- 我和他

## 3. 真正的生命意义

- 职业
- 交际
- 两性

生命的意义在于乐于关注他人，渴望成为社会大家庭一员，梦想着为人类和社会贡献自己的力量。
个人意义没有任何价值，真正的生命意义存在于个体与他人的交互作用中。

## 4. 童年对人生的影响

> 经验并非成功或失败之母。我们的生活经验对我们没有太大用处，其决定作用的是我们赋予经验的认知和意义。

- 先天残缺
- 溺爱
- 被忽视儿童

## 5. 童年记忆的重要价值

## 6. 合作的重要性

**Comment by rogerxu** [comment]
# 二、心灵与肉体

## 1. 心灵和身体的联系与冲突

## 2. 情感影响发展

## 3. 身形、性格与心智

**Comment by rogerxu** [comment]
# 三、自卑感和优越感

## 1. 自卑情结

自卑情结是指一个人在意识到他要面对一个他无法解决的问题时，表现出的无所适从。

每一位神经症患者都会不同程度地限制自己的活动范围，并避免与外界过多接触。他们想要逃避生活中的种种问题，并让自己活在自己可以控制的范围内。

## 2. 追求优越感

## 3. 设立有意义的目标

每个神经症患者都一样，他们选用的方法与他们的目标都是一致的，需要改进的是他们的目标，而不是他们的行为。

在努力追求优越感的过程中，只有为了他人的利益而前进的人和那些为了社会的发展而奋斗的人，才是能够超越生活，从而顺利获得优越感的人。

**Comment by rogerxu** [comment]
# 四、童年记忆

## 1. 理解记忆

## 2. 关于早期记忆的六个案例

所有的一集又有启发性，但最有价值的的要属一个人的最初记忆，就是一个人可以回忆起的最早的事情。最初记忆可以折射出他生活态度的雏形，染发膏我们了解到他将什么作为自己的人生起点。

## 3. 行为的根源——早期记忆

如果一个孩子总是与自己的父亲对抗，而自己又缺乏独立自主的能力，那是因为有一个宠爱自己的母亲和一个严厉对待自己的父亲。

**Comment by rogerxu** [comment]
# 五、梦

## 1. 关于梦

## 2. 弗洛伊德学派与梦

## 3. 个体心理学派与梦

做梦就是在保护我们的生活模式不被现实和常识的要求所威胁。梦的目的是自欺欺人，让我们自己陶醉其中。

## 4. 梦的构成

## 5. 典型的梦

- 飞翔的梦 - 给人们留下一种美好轻松的感觉，把克服困难和追求优越感目标视为很容易的事情。
- 从高处摔落下去的梦 - 这个人心灵保守，并担心遭受失败，而不是全心全意要克服困难。
- 赶不上车的梦 - 如果不用我自己费丝毫力气，问题就可以解决，这将多么美好啊！因此，我要绕道走，我要迟到，这样就能避免遇到火车，免得遇到不能解决的问题。
- 考试的梦 - 还没有对即将要面临的问题做好充足的准备。虽然你以前解决了这个问题，现在你必须面临再次的检验。

**Comment by rogerxu** [comment]
# 六、家庭的影响

## 1. 母亲的影响

## 2. 父亲的角色和责任

两个人结婚的目的应该是一起努力谋求幸福，让彼此过得更快乐，给自己的孩子营造一个良好的成长环境。其中不管哪一方出现问题，整个家庭都不会幸福。

## 3. 为人父母

孩子与孩子之间的年龄差距，建议时间为3年。

**Comment by rogerxu** [comment]
# 七、学校的影响

## 1. 教育的变革

我们要教会孩子自立并为他人着想。应该教他们关于文学、科学和艺术的知识，让他们为人类文明的发展做出自己的贡献，而不只是习得工作技能而已。

## 2. 教师的角色

## 3. 学校里的合作与竞争

## 4. 天赋与习得

兴趣是影响智力发展的最大因素，兴趣并不是遗传来的，影响兴趣的因素是失败和没有信心。

## 5. 区分孩子的个性

懒惰的孩子有一点好处就是：当他做了一点点工作时，别人就会夸奖他。如果是平时就很努力的孩子做的，就不会受到表扬。

**Comment by rogerxu** [comment]
#  八、青春期

## 1. 青春期心理及生理特征

## 2. 青春期的挣扎

进入青春期后许多孩子容易患上神经官能症。
女孩子通常会不自信，她们会将得到赞赏看成是自己证明价值的方法。她们很容易被男人的甜言蜜语所欺骗。

## 3. 青春期的性意识萌芽

青春期的女孩对女性角色的方案表现得更为激烈。女孩子常常做一些男孩子气的行为，例如抽烟、喝酒、骂人、打架、拉帮结伙、放纵自我等。

## 4. 正视青春期

**Comment by rogerxu** [comment]
# 九、犯罪及其预防

## 1. 犯罪心理

## 2. 罪犯的类型

其实他只是为了满足自己，让自己快乐，他对别人并没有兴趣。他是为了让自己在这方面得到别人的赞赏和崇拜。

他希望自己是受人崇拜、被人追捧的人，为了吸引女孩子的注意，他不惜给她们买单。

## 3. 合作的重要性

## 4. 如何矫治犯罪行为

**Comment by rogerxu** [comment]
# 十、职业

## 1. 平衡生活的三条纽带

职业、人际关系、性别是束缚人类的三条纽带。

## 2. 职业的早期训练

## 3. 影响职业选择的其他因素

有些人无论什么工作都不会让他感到满意，他们仅仅把职业看成是保证其优越地位的方法。

## 4. 对待职业的态度

职业有些时候成为了人们逃避爱情和社会问题的借口。许多人常常以工作繁忙为理由拒绝与人交往，拒绝谈恋爱，这也成为了他们婚姻失败的借口。

**Comment by rogerxu** [comment]
# 十一、个体与社会

## 1. 宗教信仰

## 2. 政治活动和社会活动

## 3. 利己主义

自闭症发展到最严重的程度就有可能成为精神病。

## 4. 过失犯罪

## 5. 社交兴趣与社会平等

**Comment by rogerxu** [comment]
# 十二、爱情与婚姻

## 1. 爱、合作与社会兴趣的重要性

有很多人对于人类的幸福非常淡漠。他们从来不会考虑“我可以为他人做点什么”，“我如何成为社会的有用之才”，他们常常思考的是：“我可以从中获得什么？我还能得到更多的关心吗？我是不是别人关注的焦点？”

## 2. 夫妻是平等的伙伴关系

为了保证有和谐的夫妻关系，我们需要给对方而不是自己更多的关心，也就是说，给对方的关心要胜过给自己的关心。

我发现婚姻幸福有一个基本前提：让对方感觉到他/她是最有价值的，他/她是被需要的/最优秀的；他/她是你最好的伴侣和朋友。

记住，我们考虑的布什一个人的成长环境，而是一个人对环境的看法。因为一个人可能生活在不太美满的家庭，经历了很多不幸，但这可能激发他对美好生活的向往，所以他会努力让自己的婚姻幸福。

## 3. 不适合结婚的人

有些娇生惯养长大的孩子因为不懂得婚后如何调整自我，摆正自己的角色，常常感觉到婚后被遗忘。

如果夫妻两人都是骄纵长大的孩子，那这样的婚后生活更加离谱。他们不懂得为对方考虑，又渴望事事以自己为中心，所以常常体会不到幸福感。

有些人常沉沉浸在自己幻想的爱情中：浪漫的、刺激的、感动的。这种人不能正确的认识现实的爱情，更不懂得如何对待现实中的另一半。对于浪漫爱情的幻想使得这些人在现实中找不到爱。

只知道索取不懂得付出的人是不愿意生儿育女的。在他们看来，与其浪费时间在孩子身上，不如花费时间在自己身上。孩子是人生的累赘。而这样的人，婚姻一般不会幸福。

## 4. 婚姻观与人生观

我认为两个真正相爱的人在婚姻中应该会具有这些特点：有责任感、相互信赖、忠实可靠。

**Comment by plh97** [comment]
不错不错,
